---
title: "Covid-19 analysis"
author: "Leonardo Quintero"
output:
  html_document:
    df_print: paged
---
 
# Exploratory data Analysis ####

```{r}
head(data)
```
```{r} 
dim(data)
```

#### taking a look at the structure
```{r}
str(data)
```

#### taking a look at the summary
```{r}
summary(data)
```

#### Counting missing data
```{r}
sum(is.na(data))
```

#### Cases vs Deaths worldwide
```{r}

data %>% summarize(deaths = sum(deaths), Cases = sum(cases))
```

## Exploratory Data Visualization ####
```{r}
# cases worldwide
data %>%  group_by(Country, dateRep) %>% 
    summarize(deaths = sum(deaths), cases = sum(cases)) %>% 
    ggplot(aes(dateRep, cases, colour = deaths))+
    geom_jitter() +
    labs(title = "Cases by Date Worldwide",
                       subtitle = "2020", x = "Month")
```


```{r}
# Deaths worldwide
ggplot(data, aes(x = dateRep, y = deaths, colour = cases)) +
    geom_jitter(stat = "identity", fill = "blue") +
    labs(title = "Deaths by Date Worldwide",
         subtitle = "2020", x = "Month")
```

```{r}

# Cases worldwide geom_line
data %>% filter(deaths > 3) %>% 
    group_by(dateRep) %>% 
    summarize(cases  = sum(cases)) %>% 
    ggplot(aes(dateRep, cases))+
    geom_line()+
    labs(title = "Cases by Date Worldwide with geom_line",
         subtitle = "2020", x = "Month")
```

```{r}

# Visualizing cases by date
ggplot(data, aes(x = dateRep, y = cases)) +
    geom_col()+
    labs(title = "Cases by Date",
         subtitle = "2020", x = "Month")
```

```{r}
# March

plot(data$dateRep[data$dateRep > strptime("2020-02-29", format = "%y%y-%m-%d")], 
     data$cases[data$dateRep > strptime("2020-02-29", format = "%y%y-%m-%d")], las = 1,
     xlab = "March", ylab = "")
```




```{r}

# Visualizing deaths by country > 50
data %>%
    filter(deaths > 50) %>%
    mutate(Country = reorder(Country, cases)) %>%
    ggplot(aes(Country, deaths)) +
    geom_col() +
    coord_flip() +
    labs(title = "Deaths by country > 50",
         subtitle = "2020", x = "Country")
```

```{r}

# Visualizing cases by country > 50
data %>%
    filter(cases > 1000) %>%
    mutate(Country = reorder(Country, cases)) %>%
    ggplot(aes(Country, cases)) +
    geom_col() +
    xlab(NULL) +
    coord_flip()+
    labs(title = "Cases by country > 1000",
         subtitle = "2020", x = "Country")
```

#### Cases by country ####

```{r}
# cases in the united states
data %>% filter(geoId == "US") %>% 
ggplot(aes(dateRep, cases, colour = deaths)) +
    geom_point() +
    geom_smooth()+
    labs(title = "Cases by date in the US", 
         subtitle = "2020")
```

```{r}
# Cases in Italy
data %>% filter(geoId == "IT") %>% 
    ggplot(aes(dateRep, cases, colour = deaths)) +
    geom_point() +
    geom_smooth()+
    labs(title = "Cases by date in Italy", 
         subtitle = "2020")
```

```{r}
# Cases in China
data %>% filter(geoId == "CN") %>% 
    ggplot(aes(dateRep, cases, colour = deaths)) +
    geom_point() +
    geom_smooth() +
    labs(title = "Cases by date in China", 
         subtitle = "2020")
```

```{r}
# Cases in Spain
data %>% filter(geoId == "ES") %>% 
    ggplot(aes(dateRep, cases, colour = deaths)) +
    geom_point() +
    geom_smooth()+
    labs(title = "Cases by date in Spain", 
         subtitle = "2020")
```

```{r}

#  Casesby country and comparision
US_c <- data %>%  filter( geoId == "US") %>% 
    transmute(US_cases = cases, dateRep)
IT_c <- data %>%  filter(geoId == "IT") %>% 
    transmute(IT_cases = cases)
CN_c <- data %>%  filter(geoId == "CN") %>% 
    transmute(CN_cases = cases)
ES_c <- data %>%  filter(geoId == "ES") %>% 
    transmute(ES_cases = cases)

cases <- bind_cols(US_c, IT_c, CN_c, ES_c)

melted_c <- melt(cases, id.vars = "dateRep", variable.name = "series_c", value.name = "value_c")

ggplot(melted_c, aes(dateRep, value_c, colour = series_c))+
    geom_point()+
    geom_smooth(se = F)+
    geom_rug()+
    labs(title = "Comparing cases's growth in US, IT, CN and ES", 
         subtitle = "2020", y = "Cases")
```

```{r}
# Cases compared by country
ggplot(melted_c, aes(series_c, value_c)) +
    geom_col()+
    labs(title = "Cases by country compared", 
         subtitle =  "2020", x = "Country", y = "Cases")
```


#### Boxplot cases by country
```{r}

data %>%
    filter(Country %in% c("Italy", "Spain", "China","United_States_of_America")) %>%
    ggplot(aes(x=Country,y=cases, fill = Country)) +
    geom_boxplot() + 
    facet_wrap(~month, ncol= 4) + theme(
        axis.text.x = element_text(angle=90, size=5  ),
        axis.title.y = element_text(color="cadetblue" , vjust=0.35) )
```




```{r}

# Deaths by country and comparision
US <- data %>%  filter( geoId == "US") %>% 
    transmute(US_Deaths = deaths, dateRep)
IT <- data %>%  filter(geoId == "IT") %>% 
    transmute(IT_Deaths = deaths)
CN <- data %>%  filter(geoId == "CN") %>% 
    transmute(CN_Deaths = deaths)
ES <- data %>%  filter(geoId == "ES") %>% 
    transmute(ES_Deaths = deaths)

deaths <- bind_cols(US, IT, CN, ES)

melted <- melt(deaths, id.vars = "dateRep", variable.name = "series", value.name = "value")

ggplot(melted, aes(dateRep, value, colour = series))+
    geom_point()+
    geom_smooth(se = F)+
    geom_rug()+
    labs(title = "Comparing deaths' growth in US, IT, CN and ES", 
         subtitle = "2020", y = "deaths")
```



```{r}

# Deaths by country compared
ggplot(melted, aes(series, value)) +
    geom_col()+
    labs(title = "Deaths by country compared", 
         subtitle =  "2020", x = "Country", y = "Deaths")
```

#### Boxplot deaths by country compared

```{r}
data %>%
    filter(Country %in% c("Italy", "Spain", "China","United_States_of_America")) %>%
    ggplot(aes(x=Country,y=deaths, fill = Country)) +
    geom_boxplot() + 
    facet_wrap(~month, ncol= 4) + theme(
        axis.text.x = element_text(angle=90, size=5  ),
        axis.title.y = element_text(color="cadetblue" , vjust=0.35) )
```

